echo "i = VCF file generated by snpEff; o = path to output directory; p = path to snpSift executable"
while getopts i:o:p: flag
    do
        case "${flag}" in
            i ) inpath=${OPTARG} ;;
            o ) outpath=${OPTARG} ;;
            p ) snpSift_path=${OPTARG} ;;
        esac
    done
    

## making output folder if it does not exist

if [ -d "$outpath" ]
then
    echo "Directory already exists; continuing in $outpath" && cd $outpath
else
    mkdir $outpath && cd $outpath
fi

## snpSift-ing
for data_file in $inpath/*.vcf
    do
        base=`basename $data_file .vcf`
        echo $data_file
        cat $data_file | `which perl` $snpSift_path/scripts/vcfEffOnePerLine.pl | `which java` -jar $snpSift_path/SnpSift.jar extractFields -s "," -e "." - CHROM POS REF ALT "ANN[*].EFFECT" "EFF[*].AA" "ANN[*].HGVS_P" > $base-TRIMMED.vcf
    done

## getting amino acids in more friendly format
for filtered_file in $outpath/*.vcf
    do
        echo $filtered_file
        gawk -i inplace -F"\t" 'BEGIN { OFS="\t" } { gsub(/0|1|2|3|4|5|6|7|8|9|,./,"",$7); print }' $filtered_file
    done

for filt_file in $outpath/*.vcf
    do
        echo $filt_file
        gawk -i inplace -F"\t" 'BEGIN { OFS="\t" } {print $1,$2,$3,$4,$5,$6,$7,substr($7,0,5)"-"substr($7,6,8)}' $filt_file
    done

for next_filt in $outpath/*.vcf
    do
        echo $next_filt
        gawk -i inplace -F"\t" 'BEGIN { OFS="\t" } {print $1,$2,$3,$4,$5,$6,$7,substr($8,3,9)}' $next_filt
    done

## retain only recoding/"intergenic" hits

for pre_filt in $outpath/*.vcf
    do
        echo $pre_filt
        sed -i ".bcp" "/downstream_gene_variant/d; /upstream_gene_variant/d" $pre_filt
    done
rm $outpath/*.bcp

echo Done, hopefully
